THEME_NAME: MIST
THEME_VERSION: 1.0.0
THEME_FONTS: "Arima:400,700"
POSTS_PER_PAGINATION: 11

fonts:
  size: 16
  weight: 400
  strong_font_weight: 700
  base_font_family: Arima
  line_height: 1.4

colors:
  light:
    background_color: "#000000"
    main_color: "#ffffff"
    overlay_color: "#58585866"
    tag_color: "#269486"

  dark:
    background_color: "#ffffff"
    main_color: "#000000"
    overlay_color: "#cfcfcf6e"
    tag_color: "#ffffff"


settings:
  loop:
    featured_image: true
    tags: true
    authors: true
    published_date: true

  footer:
    feed_icon: true

  post:
    authors: true
    tags: true
    featured_image: true
    variants: true
    toc: true
    published_date: true
